IMPORT REQUIRED **LIBRARIES**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.metrics import mean_squared_error,r2_score

LOAD THE BOSTON HOUSING DATASET

In [ ]:
boston = fetch_openml(name='boston',version=1,as_frame=True)
df = boston.frame
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

SEPARATE FEATURES AND TARGET

In [ ]:
X = df.drop('MEDV',axis=1)
y = df['MEDV']

TRAIN-TEST-SPLIT

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42)

TRAIN LINEAR REGRESSION MODEL

In [ ]:
Ir = LinearRegression()
Ir.fit(X_train,y_train)

LinearRegression()

PREDICTION AND EVALUATION

In [ ]:
y_pred_Ir = Ir.predict(X_test)
print("Linear Regression")
print("MSE:",mean_squared_error(y_test,y_pred_Ir))
print("R2 Score:",r2_score(y_test,y_pred_Ir))

Linear Regression
MSE: 24.291119474973478
R2 Score: 0.6687594935356326

LINEAR REGRESSION COEFFICIENTS

In [ ]:
Ir_coeff=pd.Series(Ir.coef_,index=X.columns)
Ir_coeff

CRIM       -0.113056
ZN          0.030110
INDUS       0.040381
CHAS        2.784438
NOX       -17.202633
RM          4.438835
AGE        -0.006296
DIS        -1.447865
RAD         0.262430
TAX        -0.010647
PTRATIO    -0.915456
B           0.012351
LSTAT      -0.508571
dtype: float64

TRAIN RIDGE REGRESSION MODEL

In [ ]:
ridge = Ridge(alpha=1.0)
ridge.fit(X_train,y_train)

Ridge()

TRAIN LASSO REGRESSION MODEL

In [ ]:
lasso = Lasso(alpha=0.1)
lasso.fit(X_train,y_train)

Lasso(alpha=0.1)

LASSO PREDICTION AND PREDICTION

In [ ]:
y_pred_lasso = Lasso.predict(X_test)
print("Lasso Regression")
print("MSE:",mean_squared_error(y_test,y_pred_lass0))